---
- name: deploy packagex
  hosts: localhost

  vars_files:
    - group_vars/sonarservers

  tasks:
    - name: java deployment
      import_role:
        name: java_deployment
      vars:
        - java_service: "{{ packagex.java_name }}"
      run_once: yes

    - name: sonaqube user creation
      import_role:
        name: user_creation
      vars:
        common_path: "{{ packagex.path }}"
        sonarqube_path: "{{ packagex.path }}"
        sonarqube_user: "{{ packagex.user }}"

    - name: download and extract sonar qube
      import_role:
        name: install_sonarqube
      vars:
        sonarqube_binary: "{{ packagex.binary }}"
        sonarqube_path: "{{ packagex.path }}"
        sonarqube_user: "{{ packagex.user }}"

    - name: start and wait till service come up
      import_role:
        name: start_sonar
      vars:
        sonarqube_path: "{{ packagex.path }}"
      tags: start_all
