---
- name: deploy packagex
  hosts: localhost

  vars_files:
    - group_vars/sonarservers

  tasks:
    - name: java deployment
      import_role:
        name: common/roles/java_deployment.yml
      vars:
        - java_service: "{{ packagex.java_name }}"
      run_once: yes

    - name: sonaqube user creation
      import_role:
        name: common/roles/user_creation.yml
      vars:
        common_path: "{{ packagex.path }}"
        sonarqube_path: "{{ packagex.path }}"
        sonarqube_user: "{{ packagex.user }}"

    - name: download and extract sonar qube
      import_role:
        name: common/roles/install_sonarqube.yml
      vars:
        sonarqube_binary: "{{ packagex.binary }}"
        sonarqube_path: "{{ packagex.path }}"
        sonarqube_user: "{{ packagex.user }}"

    - name: start and wait till service come up
      import_role:
        name: common/roles/start_sonar.yml
      vars:
        sonarqube_path: "{{ packagex.path }}"
      tags: start_all
