---
  - name: Check if java rpm is already installed or not
    yum:
      list: "{{ java_service }}"
      # If not installed yum_list.results[*].yumstate != installed
    register: check_java_existence
  - name : Install java
    yum:
      name: "{{ java_service }}"
      state: present
    when: check_java_existence.results | selectattr("yumstate", "match", "installed") | list | length == 0
